### PR TITLE
allow to pass children directly

### PR DESCRIPTION
**Pull request by nd0ut**

### CODE REVIEW

**Comment by sheerun** [comment]
@gnoff Do you want to merge it?

**Comment by gnoff** [comment]
@nd0ut @sheerun whoa, somehow didn't see this PR back in May and haven't recently been doing FE work. I'll check it out and probably pull. probably this weekend

**Comment by natew** [comment]
any update?

**Review by rt2zz — APPROVED** [review]

**Comment by rt2zz** [comment]
@gnoff can you cut a new release?

**Pull request merged**
